# Generated by Django 4.2.5 on 2024-01-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='event_images/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='event_thumbnails/')),
            ],
        ),
    ]
