# Generated by Django 4.2.5 on 2024-01-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cor_events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
